### ISSUE TITLE
Invalid Parameter – yii\base\InvalidParamException 

### ISSUE THREAD

**Issue by apert4160** [tangjiandeng/LyHNIMS#2]
你好，我将你整个项目gti clone下来，部署到apache下遇到了问题。

关闭debug模式访问得到“服务器内部问题”，不能正常使用。
开启debug模式得到：

Invalid Parameter – yii\base\InvalidParamException  
The file or directory to be published does not exist: /var/www/lyhosp/vendor/bower/jquery/dist

确实在目录下找不到这个dist文件夹，可以补充一下吗？

谢谢。

**Comment by donjan-deng** [comment]
已添加，最好自己Composer安装YII2
